### PR TITLE
Add in bower.json file

### PR DESCRIPTION
**Pull request by jcreamer898**
This will make `bower install amplify` work and only download the required files.

### CODE REVIEW

**Comment by dcneiner** [comment]
@jcreamer898 This would force someone to only use the full library. Wouldn't we want to at least include the separate components as part of the `main` key? I have also seen some other bower.json files that include the minified versions as part of their main.

**Comment by jcreamer898** [comment]
The `main` thing doesn't do what you think it does. Everything in `lib` ends up being available, as well as the docs.

**Comment by jcreamer898** [comment]
For example, in jQuery's bower.json...

``` json
{
  "name": "jquery",
  "version": "2.1.1pre",
  "main": "dist/jquery.js",
  "license": "MIT",
  "ignore": [
 ...
}
```

Yet, when you run `bower install jquery`

**Comment by dcneiner** [comment]
@jcreamer898 Ah, my mistake! Thanks for clarifying.

**Comment by jcreamer898** [comment]
Yup!

**Comment by jcreamer898** [comment]
P.S. A new tag will also have to be created so that bower will pull from that tag and not from master.

**Pull request merged**
